<?php

namespace ContactFormBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageCategoryRepository extends EntityRepository
{
}
