<?php

namespace ContactFormBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function findUnreadMessages()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ContactFormBundle:Message p WHERE p.readStatus = FALSE')->getResult();
    }
}
