<?php

namespace ContactFormBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
    public function changeStatus($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM WorkshopBundle:workorder p WHERE p.status = :status')->setParameter('status', $status)
            ->getResult();
    }
}
